"""Federal rows (CRA / ESDC, canada.ca) for the Canada starter pack — part 1 of 2."""
from __future__ import annotations


def add_federal() -> None:
    from canada_starter_pack_2026_09_25_rows import (  # noqa: PLC0415
        ALL_BUT_QC, ALL_BUT_QC_NT_NU, ALL_INCOMES, CCB_URL, CRA, ESDC, FILE_TAX, QC_NOTE_CPP, SIN_DOCS, F, rules,
    )

    F(
        "can-canada-child-benefit",
        "Canada Child Benefit (CCB)",
        "Tax-free monthly payment from the CRA to eligible families to help with the cost of raising children under 18. Income-tested but reaches middle and many higher-income families.",
        "July 2026 – June 2027: up to C$8,157 a year (C$679.75/month) per child under 6 and up to C$6,883 a year (C$573.58/month) per child aged 6 to 17. The amount is reduced when adjusted family net income (AFNI) is over C$38,237, with a smaller second-tier reduction above C$82,847.",
        SIN_DOCS + ["Child's birth registration (or proof of birth)"],
        "Apply when you register your baby's birth with the province (Automated Benefits Application), through CRA My Account, or with Form RC66. " + FILE_TAX,
        "https://www.canada.ca/en/revenue-agency/services/child-family-benefits/canada-child-benefit-overview/canada-child-benefit-apply.html",
        CCB_URL,
        CRA,
        ["children", "cash", "tax"] + ALL_INCOMES,
        rules(
            provinces=None,
            notes="You live with a child under 18, are primarily responsible for their care and upbringing, and are a resident of Canada for tax purposes; you or your spouse/partner is a Canadian citizen, permanent resident, protected person, temporary resident who has lived in Canada for the previous 18 months (with a valid permit in the 19th month), or registered under the Indian Act. No hard income ceiling: phase-out starts at AFNI C$38,237 (second tier C$82,847); families with several young children can still get a partial amount at high incomes.",
            verify_notes="No income cut-off: max_annual_income null and implies_low_income false by design (official phase-out, not a ceiling). Rates from CRA 'How much you can get' (July 2026 – June 2027).",
        ),
    )
    F(
        "can-child-disability-benefit",
        "Child Disability Benefit (CDB)",
        "Tax-free monthly supplement paid with the Canada Child Benefit for families caring for a child who qualifies for the disability tax credit.",
        "July 2026 – June 2027: up to C$3,480 a year (C$290/month) per eligible child. Reduced when AFNI is over C$82,847 (3.2% of income above that for one child; 5.7% for two or more).",
        SIN_DOCS + ["Approved Form T2201 (disability tax credit) for the child"],
        "Apply for the CCB and have the child's disability tax credit (Form T2201) approved — the CDB is then added automatically.",
        "https://www.canada.ca/en/revenue-agency/services/child-family-benefits/child-disability-benefit.html",
        "https://www.canada.ca/en/revenue-agency/services/child-family-benefits/child-disability-benefit.html",
        CRA,
        ["children", "disability", "cash", "middle-class", "upper-middle-class", "high-income-eligible"],
        rules(
            provinces=None,
            notes="You are eligible for the Canada Child Benefit and the child is under 18 and eligible for the disability tax credit. The disability is the child's — the parent does not need a disability.",
            verify_notes="Reduced above C$82,847 AFNI but no single zero-out ceiling (depends on children) — max_annual_income null. disability_required false because the child, not the applicant, must be DTC-eligible.",
        ),
    )
    F(
        "can-groceries-essentials-benefit",
        "Canada Groceries and Essentials Benefit (CGEB, formerly the GST/HST credit)",
        "Tax-free quarterly payment for individuals and families with low and modest incomes. Replaced the GST/HST credit in July 2026 with the same rules and a 25% increase for 2026–2031.",
        "July 2026 – June 2027: up to C$679 if single, C$890 if married or common-law, plus C$234 for each eligible child under 19. May include related provincial/territorial payments.",
        SIN_DOCS,
        "No application needed: file your tax return (new residents use Form RC151). " + FILE_TAX,
        "https://www.canada.ca/en/revenue-agency/services/child-family-benefits/canada-groceries-essentials-benefit.html",
        "https://www.canada.ca/en/revenue-agency/services/child-family-benefits/canada-groceries-essentials-benefit/who-eligible.html",
        CRA,
        ["cash", "food", "tax_credit", "low-income", "middle-class"],
        rules(
            provinces=None, min_age=19, max_annual_income=82952,
            notes="Resident of Canada for tax purposes; 19 or older (or under 19 with a spouse/partner or living with your child). AFNI must be below the official maximum for your family (2025 base year): single no children C$60,012; married/common-law no children C$64,232; 1 child C$68,912; 2 children C$73,592; 3 children C$78,272; 4 or more children C$82,952.",
            verify_notes="max_annual_income encodes the highest official threshold (C$82,952, 4+ children, 2025 base year); lower thresholds for smaller families are in notes. Under-19 exceptions (spouse/parent) apply. Old GST/HST credit page says 'no longer available' — last GST/HST credit payment April 2026.",
        ),
    )
    F(
        "can-canada-workers-benefit",
        "Canada Workers Benefit (CWB)",
        "Refundable tax credit for low-income workers, with a disability supplement. Half is paid in advance (ACWB) in July, October and January.",
        "2025 tax year: basic amount up to C$1,633 (single) or C$2,813 (family); disability supplement up to C$843. Amounts differ for residents of Quebec, Nunavut and Alberta.",
        SIN_DOCS + ["Schedule 6 with your tax return"],
        "Claim on Schedule 6 of your tax return (CRA may calculate it for you); eligible people get automatic advance payments.",
        "https://www.canada.ca/en/revenue-agency/services/child-family-benefits/canada-workers-benefit.html",
        "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/about-your-tax-return/tax-return/completing-a-tax-return/deductions-credits-expenses/line-45300-canada-workers-benefit-cwb/who-is-eligible.html",
        CRA,
        ["employment", "tax_credit", "low-income", "disability"],
        rules(
            provinces=None, min_age=19, max_annual_income=60629,
            notes="Working income; resident of Canada all year; 19 or older on Dec 31 (or living with a spouse/partner or child). Not eligible if a full-time student for more than 13 weeks (unless you have an eligible dependant) or confined to prison 90+ days. 2025 zero-out: basic single C$37,742, basic family C$49,393; disability supplement single C$43,360, family C$55,009 (C$60,629 if both spouses are DTC-eligible). Reductions start at C$26,855 single / C$30,639 family.",
            verify_notes="max_annual_income encodes the highest official zero-out (C$60,629, family where both spouses get the disability supplement); non-disabled families zero out at C$49,393 — see notes. QC/NU/AB have different amounts.",
        ),
    )
    F(
        "can-old-age-security",
        "Old Age Security (OAS) pension",
        "Monthly taxable pension for people 65 and older based on years lived in Canada. Not based on work history; reduced by the OAS recovery tax (clawback) at higher incomes.",
        "July – September 2026 maximum: C$751.97/month at 65–74 and C$827.17/month at 75+ (amounts rise about 1.4% for October – December 2026). Full pension with 40 years of residence after 18; partial with 10+ years.",
        ["Social Insurance Number (SIN)", "Proof of residence history in Canada (if not auto-enrolled)", "Bank details"],
        "Many people are enrolled automatically (letter the month after turning 64); otherwise apply online through My Service Canada Account or with the paper form.",
        "https://www.canada.ca/en/services/benefits/publicpensions/old-age-security/apply.html",
        "https://www.canada.ca/en/services/benefits/publicpensions/old-age-security.html",
        ESDC,
        ["elderly", "pension"] + ALL_INCOMES,
        rules(
            provinces=None, min_age=65,
            notes="65 or older; Canadian citizen or legal resident; lived in Canada at least 10 years after age 18 (20 years if living outside Canada). OAS recovery tax (clawback): 15% of net world income above C$93,454 (2025 income, affects July 2026 – June 2027) — full pension recovered at about C$152,062 (65–74) or C$157,923 (75+); 2026 income threshold C$95,323.",
            verify_notes="Universal residence-based pension: max_annual_income null (clawback is a tax, noted). Rates from canada.ca OAS payments page (July–September 2026).",
        ),
    )
    F(
        "can-guaranteed-income-supplement",
        "Guaranteed Income Supplement (GIS)",
        "Monthly non-taxable top-up for low-income Old Age Security pensioners living in Canada.",
        "July – September 2026 maximum per month: single, widowed or divorced C$1,123.17; spouse receives full OAS C$676.09; spouse receives the Allowance C$676.09; spouse does not receive OAS C$1,123.17.",
        ["Social Insurance Number (SIN)", "Filed tax returns (you and spouse)", "Bank details"],
        "Often automatic with OAS; otherwise apply online through My Service Canada Account or by form. Keep filing tax returns to keep receiving it.",
        "https://www.canada.ca/en/services/benefits/publicpensions/old-age-security/guaranteed-income-supplement/apply.html",
        "https://www.canada.ca/en/services/benefits/publicpensions/old-age-security/guaranteed-income-supplement.html",
        ESDC,
        ["elderly", "pension", "income_support", "low-income"],
        rules(
            provinces=None, min_age=65, max_annual_income=54624,
            notes="Receiving the OAS pension, living in Canada, and annual income (excluding OAS) below the limit: single under C$22,800; couple with spouse on full OAS under C$30,096 combined; spouse on the Allowance under C$42,144 combined; spouse not receiving OAS under C$54,624 combined.",
            verify_notes="max_annual_income encodes the highest official limit (C$54,624 combined, spouse without OAS); single limit C$22,800 in notes. Income excludes OAS itself.",
        ),
    )
    F(
        "can-oas-allowance",
        "Allowance (OAS program, ages 60–64)",
        "Monthly benefit for low-income people aged 60 to 64 whose spouse or common-law partner receives the Guaranteed Income Supplement.",
        "July – September 2026: up to C$1,428.06 per month.",
        ["Social Insurance Number (SIN)", "Proof of marriage or common-law union", "Filed tax returns (you and spouse)"],
        "Apply to Service Canada (online or by form); may be automatic in some cases.",
        "https://www.canada.ca/en/services/benefits/publicpensions/old-age-security/guaranteed-income-supplement/allowance.html",
        "https://www.canada.ca/en/services/benefits/publicpensions/old-age-security/guaranteed-income-supplement/allowance.html",
        ESDC,
        ["elderly", "income_support", "low-income", "marriage"],
        rules(
            provinces=None, min_age=60, max_age=64, max_annual_income=42144, marital_status=["married"],
            notes="Aged 60–64; spouse or common-law partner receives GIS; Canadian citizen or legal resident living in Canada; lived in Canada 10+ years after 18; combined annual income under C$42,144.",
            verify_notes="Official combined income limit C$42,144 encoded. Common-law partners also qualify (catalogue marital value 'married' covers both).",
        ),
    )
    F(
        "can-oas-allowance-survivor",
        "Allowance for the Survivor (ages 60–64)",
        "Monthly benefit for low-income widowed people aged 60 to 64 who have not remarried or entered a new common-law relationship.",
        "July – September 2026: up to C$1,702.34 per month.",
        ["Social Insurance Number (SIN)", "Death certificate of spouse/partner", "Filed tax returns"],
        "Apply to Service Canada (online or by form).",
        "https://www.canada.ca/en/services/benefits/publicpensions/old-age-security/guaranteed-income-supplement/allowance-survivor.html",
        "https://www.canada.ca/en/services/benefits/publicpensions/old-age-security/guaranteed-income-supplement/allowance-survivor.html",
        ESDC,
        ["elderly", "widow", "income_support", "low-income"],
        rules(
            provinces=None, min_age=60, max_age=64, max_annual_income=30696, marital_status=["widow"],
            notes="Aged 60–64; spouse or common-law partner has died and you have not remarried or entered a new common-law relationship; living in Canada; 10+ years in Canada after 18; annual income under C$30,696.",
            verify_notes="Official income limit C$30,696 encoded.",
        ),
    )
    F(
        "can-cpp-retirement",
        "Canada Pension Plan (CPP) retirement pension",
        "Monthly taxable pension based on your contributions from work in Canada outside Quebec. Can start from age 60 (reduced) up to 70 (increased).",
        "Maximum at age 65 (starting January 2026): C$1,507.65 per month; average for new retirees C$877.01. Taken early (60) it is reduced; delayed to 70 it is increased.",
        ["Social Insurance Number (SIN)", "Bank details", "Proof of age (if requested)"],
        "Apply online through My Service Canada Account (up to 12 months before you want it to start) or by paper form.",
        "https://www.canada.ca/en/services/benefits/publicpensions/cpp/apply.html",
        "https://www.canada.ca/en/services/benefits/publicpensions/cpp.html",
        ESDC,
        ["pension", "elderly", "employment"] + ALL_INCOMES,
        rules(
            provinces=ALL_BUT_QC, min_age=60,
            notes="At least 60 years old and made at least one valid contribution to the CPP. Not income-tested. " + QC_NOTE_CPP,
            verify_notes="Contributory, not income-tested: max_annual_income null. Quebec excluded (QPP).",
        ),
    )
    F(
        "can-cpp-disability",
        "CPP disability benefit",
        "Monthly taxable benefit for CPP contributors under 65 who cannot work regularly because of a severe and prolonged disability.",
        "Maximum 2026: C$1,741.20 per month, plus possible benefits for dependent children.",
        ["Social Insurance Number (SIN)", "Medical report completed by your health professional", "Work and contribution history"],
        "Apply online through My Service Canada Account or by the paper application with the medical report.",
        "https://www.canada.ca/en/services/benefits/publicpensions/cpp/cpp-disability-benefit/apply.html",
        "https://www.canada.ca/en/services/benefits/publicpensions/cpp/cpp-disability-benefit.html",
        ESDC,
        ["disability", "pension", "employment", "middle-class", "upper-middle-class"],
        rules(
            provinces=ALL_BUT_QC, min_age=18, max_age=64, disability_required=True,
            notes="Under 65; enough CPP contributions (recent-contribution rules apply); a severe and prolonged mental or physical disability that stops you from doing any substantially gainful work regularly. Quebec residents apply for the QPP disability pension (Retraite Québec).",
            verify_notes="Contribution tests vary (e.g. 4 of last 6 years, or 3 of 6 with 25+ years). Quebec: QPP disability pension instead.",
        ),
    )
    F(
        "can-cpp-survivor",
        "CPP survivor's pension",
        "Monthly pension paid to the surviving spouse or common-law partner of a deceased CPP contributor.",
        "If you are 65+: 60% of the contributor's retirement pension (subject to maximums). Under 65: a flat rate plus 37.5% of the contributor's pension.",
        ["Social Insurance Number (SIN)", "Death certificate", "Proof of marriage or common-law union"],
        "Apply to Service Canada online or by the survivor's pension application form.",
        "https://www.canada.ca/en/services/benefits/publicpensions/cpp/cpp-survivor-pension.html",
        "https://www.canada.ca/en/services/benefits/publicpensions/cpp/cpp-survivor-pension.html",
        ESDC,
        ["widow", "pension"] + ALL_INCOMES,
        rules(
            provinces=ALL_BUT_QC, marital_status=["widow"],
            notes="The deceased made enough CPP contributions; you were their spouse or common-law partner at death (separated common-law partners generally not eligible). Not income-tested. Quebec residents: QPP surviving spouse's pension (Retraite Québec).",
            verify_notes="Minimum contribution period depends on the contributor's age; confirm with Service Canada.",
        ),
    )
    F(
        "can-ei-regular",
        "Employment Insurance (EI) regular benefits",
        "Temporary income support for insured workers who lose their job through no fault of their own and are ready and able to work.",
        "55% of average insurable weekly earnings, up to C$729 a week in 2026 (maximum insurable earnings C$68,900). Paid for 14 to 45 weeks depending on local unemployment and hours worked.",
        ["Social Insurance Number (SIN)", "Record(s) of Employment", "Bank details", "Employer names and dates"],
        "Apply online as soon as you stop working (within 4 weeks); employers submit your Record of Employment.",
        "https://www.canada.ca/en/services/benefits/ei/ei-regular-benefit/apply.html",
        "https://www.canada.ca/en/services/benefits/ei/ei-regular-benefit.html",
        ESDC,
        ["employment", "unemployment", "insurance", "middle-class", "upper-middle-class"],
        rules(
            provinces=None,
            notes="Worked in insurable employment and have 420–700 insured hours in the last 52 weeks (depends on your region's unemployment rate); lost the job through no fault of your own; without work and pay for 7 consecutive days; ready, willing and able to work and actively looking. Applies in all provinces including Quebec.",
            verify_notes="Earnings-replacement insurance, not income-tested: max_annual_income null.",
        ),
    )
    F(
        "can-ei-maternity-parental",
        "EI maternity and parental benefits",
        "Earnings-replacement benefits for insured workers who are pregnant, recently gave birth, or are caring for a newborn or newly adopted child (outside Quebec).",
        "Maternity: up to 15 weeks at 55% (max C$729/week, 2026). Parental — standard: up to 40 weeks shared (one parent max 35) at 55%; extended: up to 69 weeks shared (one parent max 61) at 33% (max C$437/week).",
        ["Social Insurance Number (SIN)", "Record(s) of Employment", "Child's expected or actual birth date / adoption placement date", "Bank details"],
        "Apply online to Service Canada as soon as you stop working; choose standard or extended parental benefits (the choice is final once payments start).",
        "https://www.canada.ca/en/services/benefits/ei/ei-maternity-parental/apply.html",
        "https://www.canada.ca/en/services/benefits/ei/ei-maternity-parental.html",
        ESDC,
        ["maternity", "children", "employment", "insurance", "middle-class", "upper-middle-class", "high-income-eligible"],
        rules(
            provinces=ALL_BUT_QC,
            notes="600 insured hours in the last 52 weeks (or since your last claim); regular weekly earnings reduced by more than 40% for at least one week. Quebec residents use the Québec Parental Insurance Plan (see can-qc-qpip); self-employed people can opt in. Not income-tested.",
            verify_notes="Earnings-replacement, not means-tested: max_annual_income null. Quebec excluded (QPIP).",
        ),
    )
    F(
        "can-ei-sickness",
        "EI sickness benefits",
        "Earnings replacement for insured workers who cannot work because of illness, injury or quarantine.",
        "Up to 26 weeks at 55% of average insurable weekly earnings (max C$729/week in 2026).",
        ["Social Insurance Number (SIN)", "Record(s) of Employment", "Medical certificate (keep for 6 years)"],
        "Apply online to Service Canada as soon as you stop working.",
        "https://www.canada.ca/en/services/benefits/ei/ei-sickness/apply.html",
        "https://www.canada.ca/en/services/benefits/ei/ei-sickness.html",
        ESDC,
        ["health", "employment", "insurance", "middle-class", "upper-middle-class"],
        rules(
            provinces=None,
            notes="600 insured hours in the last 52 weeks; unable to work for medical reasons; regular weekly earnings reduced by more than 40% for at least one week. Applies in all provinces including Quebec.",
            verify_notes="Not income-tested: max_annual_income null.",
        ),
    )
    F(
        "can-ei-caregiving",
        "EI caregiving benefits (family caregiver and compassionate care)",
        "Earnings replacement for insured workers who take time off to care for a critically ill or injured family member, or someone needing end-of-life care.",
        "55% of average insurable weekly earnings (max C$729/week, 2026): up to 35 weeks for a critically ill or injured child, 15 weeks for an adult, 26 weeks of compassionate care for end-of-life care.",
        ["Social Insurance Number (SIN)", "Record(s) of Employment", "Medical certificate signed by the patient's doctor or nurse practitioner"],
        "Apply online to Service Canada; the medical certificate can be submitted separately.",
        "https://www.canada.ca/en/services/benefits/ei/caregiving.html",
        "https://www.canada.ca/en/services/benefits/ei/caregiving.html",
        ESDC,
        ["caregiver", "employment", "insurance", "middle-class", "upper-middle-class"],
        rules(
            provinces=None,
            notes="600 insured hours in the last 52 weeks; regular weekly earnings reduced by more than 40% for at least one week; family member certified as critically ill/injured or needing end-of-life care. Applies in all provinces including Quebec.",
            verify_notes="Not income-tested: max_annual_income null.",
        ),
    )
    F(
        "can-canada-disability-benefit",
        "Canada Disability Benefit",
        "Monthly federal payment for low-income working-age people with disabilities who have the disability tax credit. Payments began July 2025.",
        "July 2026 – June 2027: up to C$204.20 per month (income-tested). Working income exemption C$10,210 (single) or C$14,294 (couple). A one-time C$150 supplemental payment was issued on September 17, 2026 to eligible recipients.",
        SIN_DOCS + ["Approved disability tax credit", "2025 tax returns for you and your spouse/partner"],
        "Apply online, by phone, in person at Service Canada or by mail once your DTC is approved; retroactive payments up to 24 months may be possible.",
        "https://www.canada.ca/en/services/benefits/disability/canada-disability-benefit/apply.html",
        "https://www.canada.ca/en/services/benefits/disability/canada-disability-benefit.html",
        ESDC,
        ["disability", "income_support", "low-income", "cash"],
        rules(
            provinces=None, min_age=18, max_age=64, disability_required=True, implies_low_income=True,
            notes="Aged 18–64; approved for the disability tax credit; resident of Canada for tax purposes; you (and your spouse/partner) filed 2025 tax returns; Canadian citizen, permanent resident, registered under the Indian Act, protected person, or temporary resident living in Canada for the past 18 months. Amount reduced as adjusted family net income rises (working income exemptions apply). Active as of September 2026.",
            verify_notes="Income-tested on AFNI; zero-out income not encoded — catalogue Canada soft gate (C$58,523, heuristic) applies via implies_low_income. Confirm exact reduction rates on canada.ca 'How much you could get'.",
        ),
    )
    F(
        "can-disability-tax-credit",
        "Disability tax credit (DTC)",
        "Non-refundable federal tax credit for people with a severe and prolonged impairment (or their supporting family member). Also the gateway to the RDSP, Child Disability Benefit and Canada Disability Benefit.",
        "Reduces income tax payable; a supporting family member can claim unused amounts; a supplement applies for eligible children. DTC approval unlocks the Child Disability Benefit, RDSP grants/bonds and the Canada Disability Benefit.",
        ["Form T2201 certified by a medical practitioner", "Social Insurance Number (SIN)"],
        "Have a medical practitioner certify Form T2201 (digital or paper) and send it to the CRA; you can apply any time.",
        "https://www.canada.ca/en/revenue-agency/services/tax/individuals/segments/tax-credits-deductions-persons-disabilities/disability-tax-credit/how-apply.html",
        "https://www.canada.ca/en/revenue-agency/services/tax/individuals/segments/tax-credits-deductions-persons-disabilities/disability-tax-credit.html",
        CRA,
        ["disability", "tax_credit"] + ALL_INCOMES,
        rules(
            provinces=None, disability_required=True,
            notes="Severe and prolonged impairment (expected to last 12+ months) in physical or mental functions certified on Form T2201: marked restriction in at least one category, significant restriction in two or more categories (cumulative effect), or need for life-sustaining therapy. Not income-tested (non-refundable — useful when you or a supporting relative owe tax).",
            verify_notes="Not income-tested: max_annual_income null.",
        ),
    )
    F(
        "can-rdsp",
        "Registered Disability Savings Plan (RDSP) with Canada Disability Savings Grant and Bond",
        "Long-term savings plan for a person approved for the disability tax credit, with federal matching grants and a low-income bond.",
        "Canada Disability Savings Grant: matching up to C$3,500 a year (C$70,000 lifetime) until the end of the year the beneficiary turns 49 — a C$1,500 contribution can attract the maximum at lower incomes. Canada Disability Savings Bond: up to C$1,000 a year (C$20,000 lifetime) for low/modest-income families, no contribution needed. 10 years of unused grant/bond entitlements can be carried forward. C$200,000 lifetime contribution limit.",
        ["Beneficiary's SIN", "Approved disability tax credit", "Holder's SIN (parent/guardian if beneficiary is a minor)"],
        "Open an RDSP at a participating financial institution and ask it to apply for the grant and bond.",
        "https://www.canada.ca/en/employment-social-development/programs/disability/savings.html",
        "https://www.canada.ca/en/employment-social-development/programs/disability/savings/how-much.html",
        ESDC,
        ["disability", "savings", "grant"] + ALL_INCOMES,
        rules(
            provinces=None, max_age=59, disability_required=True,
            notes="Beneficiary is eligible for the disability tax credit, a Canadian resident with a SIN, and under 60 (contributions until the end of the year they turn 59). Grant matching rate and bond depend on family net income; higher-income families still get a C$1-for-C$1 grant (up to C$1,000/year).",
            verify_notes="All incomes eligible for the account and some grant; bond is low-income only — max_annual_income null.",
        ),
    )
    F(
        "can-resp-cesg",
        "RESP with Canada Education Savings Grant (CESG)",
        "Registered Education Savings Plan for a child's post-secondary education; the federal government adds a grant on contributions.",
        "CESG: 20% of the first C$2,500 contributed each year (C$500/year), up to C$7,200 lifetime per child until the end of the year the child turns 17. Additional CESG on the first C$500: +C$100 if AFNI is C$58,523 or less, +C$50 if between C$58,523 and C$117,045 (2026). BC and Quebec residents may get extra provincial amounts.",
        ["Child's SIN", "Subscriber's SIN", "Child's proof of birth"],
        "Open an RESP with a participating provider (bank, credit union, group plan); ask the provider to apply for the CESG.",
        "https://www.canada.ca/en/services/benefits/education/education-savings/resp.html",
        "https://www.canada.ca/en/services/benefits/education/education-savings/estimating-amounts.html",
        ESDC,
        ["children", "education", "savings", "grant"] + ALL_INCOMES,
        rules(
            provinces=None,
            notes="Beneficiary (the child) is a Canadian resident with a SIN; CESG paid until the end of the year the child turns 17 (special rules for ages 16–17). Parents, grandparents or others can open the RESP. Basic 20% grant for all incomes; additional grant for low and middle incomes.",
            verify_notes="All incomes eligible for basic CESG: max_annual_income null. No age rule encoded because the applicant is usually the parent/subscriber, not the child.",
        ),
    )
    F(
        "can-canada-learning-bond",
        "Canada Learning Bond (CLB)",
        "Federal money deposited into an RESP for children from low-income families — no contribution required.",
        "C$500 in the first year of eligibility plus C$100 a year up to age 15, up to C$2,000 per child.",
        ["Child's SIN", "Primary caregiver's SIN", "RESP with a participating provider"],
        "Open an RESP and ask the provider to request the CLB (can be requested until the child's 21st birthday). From April 2028, RESPs will be opened automatically for eligible children born in 2024 or later.",
        "https://www.canada.ca/en/services/benefits/education/education-savings/canada-learning-bond.html",
        "https://www.canada.ca/en/services/benefits/education/education-savings/canada-learning-bond.html",
        ESDC,
        ["children", "education", "savings", "grant", "low-income"],
        rules(
            provinces=None, max_annual_income=73577,
            notes="Child born January 1, 2004 or later, Canadian resident with a SIN; family income limits for July 2026 – June 2027 (2025 base year): 1–3 children C$58,523 or less; 4 children under C$66,036; 5 children under C$73,577 (more than 5: call 1-800-O-Canada).",
            verify_notes="max_annual_income encodes the highest published limit (C$73,577, 5 children); 1–3 children C$58,523 — see notes.",
        ),
    )
    F(
        "can-tfsa",
        "Tax-Free Savings Account (TFSA)",
        "Registered account where investment income and withdrawals are tax-free. Open to every eligible adult regardless of income.",
        "2026 annual dollar limit C$7,000; unused room carries forward, and withdrawals are added back to room the next year.",
        ["Social Insurance Number (SIN)", "Proof of identity"],
        "Open a TFSA at a bank, credit union, trust or insurance company, or investment dealer.",
        "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/tax-free-savings-account.html",
        "https://www.canada.ca/en/revenue-agency/services/tax/registered-plans-administrators/pspa/mp-rrsp-dpsp-tfsa-limits-ympe.html",
        CRA,
        ["savings", "tax"] + ALL_INCOMES,
        rules(
            provinces=None, min_age=18,
            notes="Resident of Canada, at least 18 (in provinces where the age of majority is 19 you open it at 19, but room accrues from 18), with a valid SIN. No income limit.",
            verify_notes="Universal: max_annual_income null.",
        ),
    )
    F(
        "can-rrsp",
        "Registered Retirement Savings Plan (RRSP)",
        "Tax-deferred retirement savings: contributions are deductible from income and growth is tax-sheltered until withdrawal.",
        "Contribution limit: 18% of previous year's earned income up to C$33,810 for 2026 (C$35,390 for 2027), plus unused room; deductions reduce taxable income.",
        ["Social Insurance Number (SIN)", "Notice of assessment (shows RRSP deduction limit)"],
        "Open an RRSP with a financial institution; check your deduction limit on your notice of assessment or CRA My Account.",
        "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/rrsps-related-plans/registered-retirement-savings-plan-rrsp.html",
        "https://www.canada.ca/en/revenue-agency/services/tax/registered-plans-administrators/pspa/mp-rrsp-dpsp-tfsa-limits-ympe.html",
        CRA,
        ["savings", "tax", "pension", "middle-class", "upper-middle-class", "high-income-eligible"],
        rules(
            provinces=None, max_age=71,
            notes="Earned income and RRSP deduction room (18% of earned income, minus pension adjustments). Must be converted (e.g. to a RRIF) by the end of the year you turn 71. No income ceiling.",
            verify_notes="No income ceiling: max_annual_income null.",
        ),
    )
    F(
        "can-fhsa",
        "First Home Savings Account (FHSA)",
        "Registered account for first-time home buyers: contributions are tax-deductible and qualifying withdrawals for a first home are tax-free.",
        "C$8,000 annual participation room (C$40,000 lifetime); up to C$8,000 of unused room carries forward. Deductible like an RRSP and tax-free out like a TFSA when buying a qualifying first home.",
        ["Social Insurance Number (SIN)", "Declaration of first-time home buyer status"],
        "Open an FHSA with a financial institution that offers them.",
        "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/first-home-savings-account.html",
        "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/first-home-savings-account/opening-your-fhsas.html",
        CRA,
        ["housing", "savings", "tax"] + ALL_INCOMES,
        rules(
            provinces=None, min_age=18, max_age=71,
            notes="Resident of Canada; at least 18 (or the age of majority in your province) and not older than 71 on Dec 31; first-time home buyer — you did not live in a home you (or your spouse/partner) owned in the current year or previous 4 calendar years. No income limit.",
            verify_notes="No income ceiling: max_annual_income null.",
        ),
    )
    F(
        "can-home-buyers-plan",
        "Home Buyers' Plan (HBP)",
        "Lets first-time home buyers (and people buying for a relative with a disability) withdraw from their RRSPs tax-free to buy or build a qualifying home.",
        "Withdraw up to C$60,000 from your RRSPs; repay over 15 years. For first withdrawals made in 2026–2028, repayment starts in the fifth year after the withdrawal (temporary deferral).",
        ["Form T1036 (HBP request to withdraw)", "Written agreement to buy or build a qualifying home", "Social Insurance Number (SIN)"],
        "Complete Form T1036 and give it to your RRSP issuer for each withdrawal.",
        "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/rrsps-related-plans/what-home-buyers-plan.html",
        "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/rrsps-related-plans/what-home-buyers-plan.html",
        CRA,
        ["housing", "savings", "tax", "middle-class", "upper-middle-class", "high-income-eligible"],
        rules(
            provinces=None,
            notes="Resident of Canada; first-time home buyer (no owner-occupied home in the current or previous 4 years, with exceptions for marriage/common-law breakdown) or buying for a related person with a disability; written agreement for a qualifying home you intend to occupy within a year; money in an RRSP. No income limit.",
            verify_notes="No income ceiling: max_annual_income null.",
        ),
    )
    F(
        "can-home-buyers-amount",
        "Home buyers' amount (line 31270)",
        "Non-refundable federal tax credit for first-time home buyers or persons with a disability buying a more accessible home.",
        "Claim up to C$10,000 (worth up to C$1,500 in federal tax).",
        ["Proof of purchase (statement of adjustments)", "Social Insurance Number (SIN)"],
        "Claim on line 31270 of your tax return for the year you bought the home.",
        "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/about-your-tax-return/tax-return/completing-a-tax-return/deductions-credits-expenses/line-31270-home-buyers-amount.html",
        "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/about-your-tax-return/tax-return/completing-a-tax-return/deductions-credits-expenses/line-31270-home-buyers-amount.html",
        CRA,
        ["housing", "tax_credit", "middle-class", "upper-middle-class", "high-income-eligible"],
        rules(
            provinces=None,
            notes="You or your spouse/partner acquired a qualifying home registered in your name and you intend to live in it within a year; first-time home buyer (no owner-occupied home in the current or previous 4 years) or eligible for the disability tax credit. No income limit.",
            verify_notes="No income ceiling: max_annual_income null.",
        ),
    )
    F(
        "can-canada-dental-care-plan",
        "Canadian Dental Care Plan (CDCP)",
        "Federal dental coverage for residents without access to dental insurance and with adjusted family net income under C$90,000. Open to all eligible age groups for 2026–27.",
        "Covers a range of oral health services (cleanings, exams, x-rays, fillings, dentures and more). No co-payment if AFNI is under C$70,000; co-payments apply at C$70,000–C$89,999.",
        SIN_DOCS + ["Confirmation you have no access to dental insurance"],
        "Apply online, by phone or in person at Service Canada (children under 18 are added by a parent).",
        "https://www.canada.ca/en/services/benefits/dental/dental-care-plan/apply.html",
        "https://www.canada.ca/en/services/benefits/dental/dental-care-plan/qualify.html",
        ESDC,
        ["health", "dental", "low-income", "middle-class"],
        rules(
            provinces=None, max_annual_income=89999,
            notes="No access to dental insurance (e.g. through an employer, pension or professional association); adjusted family net income under C$90,000; resident of Canada for tax purposes; you (and your spouse/partner) filed your previous-year tax returns.",
            verify_notes="Official ceiling: AFNI under C$90,000 (encoded as 89,999). Co-pay percentages: see canada.ca 'Coverage'.",
        ),
    )
    F(
        "can-canada-student-grant-full-time",
        "Canada Student Grant for Full-Time Students",
        "Non-repayable federal grant for full-time post-secondary students from low- and middle-income families (applied for through your province or territory's student aid).",
        "Up to C$4,200 per school year (C$525 per month of study) until the end of 2026–27. Amount depends on family income and size; partial grants up to the cut-off.",
        ["Social Insurance Number (SIN)", "Proof of enrolment at a designated school", "Family income information (tax returns)"],
        "Apply through your provincial or territorial student aid office — one application covers federal and provincial aid.",
        "https://www.canada.ca/en/services/benefits/education/student-aid/grants-loans.html",
        "https://www.canada.ca/en/services/benefits/education/student-aid/grants-loans/full-time.html",
        ESDC,
        ["education", "student", "college", "grant", "need_based", "low-income", "middle-class"],
        rules(
            provinces=ALL_BUT_QC_NT_NU, max_annual_income=161321,
            notes="Full-time student at a designated post-secondary school (most private for-profit schools not eligible from August 1, 2026) with financial need. Family income thresholds from August 1, 2026 (maximum grant below the first figure, partial up to the cut-off): family of 1 C$38,474 / C$69,987; family of 4 C$76,952 / C$129,769; family of 7+ cut-off C$161,321. Not available in Quebec, Northwest Territories or Nunavut (they run their own programs).",
            verify_notes="max_annual_income encodes the highest official cut-off (C$161,321, family of 7+); smaller families have lower cut-offs — see notes. Grant amount after 2026–27 not yet published.",
        ),
    )
    F(
        "can-canada-student-grant-part-time",
        "Canada Student Grant for Part-Time Students",
        "Non-repayable federal grant for part-time post-secondary students with financial need.",
        "Up to C$2,520 per school year, depending on family income and size.",
        ["Social Insurance Number (SIN)", "Proof of part-time enrolment", "Family income information"],
        "Apply through your provincial or territorial student aid office.",
        "https://www.canada.ca/en/services/benefits/education/student-aid/grants-loans/part-time.html",
        "https://www.canada.ca/en/services/benefits/education/student-aid/grants-loans/part-time.html",
        ESDC,
        ["education", "student", "college", "grant", "need_based", "low-income", "middle-class"],
        rules(
            provinces=ALL_BUT_QC_NT_NU, max_annual_income=161321,
            notes="Part-time student at a designated school with financial need; family-income thresholds follow the full-time grant (cut-off from C$69,987 for a family of 1 up to C$161,321 for 7+). Not available in Quebec, Northwest Territories or Nunavut.",
            verify_notes="max_annual_income encodes the highest official cut-off (family of 7+).",
        ),
    )
    F(
        "can-canada-caregiver-credit",
        "Canada caregiver amount (Canada caregiver credit)",
        "Non-refundable tax credit for people supporting a spouse, partner or dependant with a physical or mental impairment.",
        "C$2,687 added to certain amounts (lines 30300/30400/30500) for an infirm dependant, or up to C$8,601 (lines 30425/30450) for an infirm spouse/partner or dependant 18 or older; reduced if the dependant's net income is high.",
        ["Signed statement from a medical practitioner (if CRA asks)", "Dependant's net income"],
        "Claim on your tax return (lines 30300, 30400, 30425, 30450 or 30500).",
        "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/about-your-tax-return/tax-return/completing-a-tax-return/deductions-credits-expenses/canada-caregiver-amount.html",
        "https://www.canada.ca/en/revenue-agency/services/tax/individuals/topics/about-your-tax-return/tax-return/completing-a-tax-return/deductions-credits-expenses/canada-caregiver-amount.html",
        CRA,
        ["caregiver", "disability", "tax_credit"] + ALL_INCOMES,
        rules(
            provinces=None,
            notes="You support a spouse/common-law partner or dependant who depends on you because of a physical or mental impairment. The caregiver's own income is not capped; the credit is reduced by the dependant's net income.",
            verify_notes="Not income-tested for the claimant: max_annual_income null.",
        ),
    )
